# Generated by Django 4.0 on 2022-01-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstname', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distribution',
            table='distribution',
        ),
        migrations.AlterModelTable(
            name='dynasty',
            table='dynasty',
        ),
        migrations.AlterModelTable(
            name='famous',
            table='famous',
        ),
        migrations.AlterModelTable(
            name='province',
            table='province',
        ),
        migrations.AlterModelTable(
            name='secondname',
            table='surname',
        ),
    ]
