# Generated by Django 4.0 on 2022-01-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstname', '0002_alter_distribution_table_alter_dynasty_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='姓氏',
            field=models.ManyToManyField(related_name='D_surname', to='firstname.SecondName'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='省份',
            field=models.ManyToManyField(related_name='D_province', to='firstname.Province'),
        ),
        migrations.AlterField(
            model_name='famous',
            name='姓氏',
            field=models.ManyToManyField(related_name='F_surname', to='firstname.SecondName'),
        ),
        migrations.AlterField(
            model_name='famous',
            name='省份',
            field=models.ManyToManyField(related_name='F_province', to='firstname.Province'),
        ),
    ]
