# Generated by Django 4.0 on 2022-01-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstname', '0003_alter_distribution_姓氏_alter_distribution_省份_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynasty',
            name='begin',
            field=models.IntegerField(verbose_name='起始时间'),
        ),
        migrations.AlterField(
            model_name='dynasty',
            name='end',
            field=models.IntegerField(verbose_name='终止时间'),
        ),
        migrations.AlterField(
            model_name='famous',
            name='begin',
            field=models.IntegerField(verbose_name='出生时间'),
        ),
        migrations.AlterField(
            model_name='famous',
            name='end',
            field=models.IntegerField(verbose_name='死亡时间'),
        ),
        migrations.AlterField(
            model_name='famous',
            name='name',
            field=models.CharField(max_length=15, verbose_name='姓名'),
        ),
    ]
