# Generated by Django 4.0 on 2022-01-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstname', '0005_alter_dynasty_begin_alter_dynasty_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynasty',
            name='begin',
            field=models.IntegerField(blank=True, null=True, verbose_name='起始时间'),
        ),
        migrations.AlterField(
            model_name='dynasty',
            name='end',
            field=models.IntegerField(blank=True, null=True, verbose_name='终止时间'),
        ),
    ]
