# Generated by Django 4.0 on 2022-01-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstname', '0006_alter_dynasty_begin_alter_dynasty_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondname',
            name='counter',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
