# Generated by Django 4.0 on 2022-01-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstname', '0007_secondname_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondname',
            old_name='counter',
            new_name='count',
        ),
    ]
